pull_request_rules:
  - name: automatic merge for master
    conditions:
      - "#approved-reviews-by>=0"
    actions:
      label:
        add: ['hacktoberfest-accepted']
      merge:
        method: merge
